swagger: '2.0'
info:
  title: 'Rust Axum SQLX 1'
  description: ''
  version: 0.0.1
host: "localhost:8085" 
schemes: 
  - http
produces:
  - application/json
paths:
  /users:
    get:
      summary: get 10 users
      operationId: get_users
      parameters:
        - name: "name"
          in: "query"
          description: "user name"
          required: false
          type: "string"
      responses: 
        '200':
          description: return users
          schema:
            type: "array"
            items: 
              $ref: "#/definitions/User"
definitions:
  User: 
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      name:
        type: "string"
      msg:
        type: "string"
      age:
        type: "integer"
        format: "int16"
      